export const FETCH_USERS_DETAILS = "FETCH_USERS_DETAILS"; ///
export const FETCH_SINGLE_USER_DETAILS = "FETCH_SINGLE_USER_DETAILS"; ///
export const DATA_DELETED = "DATA_DELETED"; ///
export const CHANGE_CONDUCTED_IN_DELETE = "CHANGE_CONDUCTED_IN_DELETE"; ///
export const EDIT_CONDUCTED = "EDIT_CONDUCTED"; ///
export const USER_ADDED = "USER_ADDED"; ///
export const NO_OF_EMP = "NO_OF_EMP"; ///
export const CHANGE_DATA_CONDUCTED = "CHANGE_DATA_CONDUCTED"; ///
export const SET_ALERT_MESSAGE = "SET_ALERT_MESSAGE"; ///
export const RESET_ALERT_MESSAGE = "RESET_ALERT_MESSAGE"; ///
export const RESET_NOTIFICATION = "RESET_NOTIFICATION"; ///
export const SET_ADDTOCONTACT_NOTIFICATION = "SET_ADDTOCONTACT_NOTIFICATION";
export const RESET_ADDTOCONTACT_NOTIFICATION =
  "RESET_ADDTOCONTACT_NOTIFICATION";
export const SET_DATATO_CARDS = "SET_DATATO_CARDS";
export const RESET_CARDS_NOTIFICATION = "RESET_CARDS_NOTIFICATION";

export const LOGIN_DETAILS = "LOGIN_DETAILS";
export const RESET_CONFIRM_LOGIN = "RESET_CONFIRM_LOGIN";
export const SIGNUP_DETAILS = "SIGNUP_DETAILS";
export const RESET_SIGNUP = "RESET_SIGNUP";
export const SET_TOKEN = "SET_TOKEN";
export const RESET_TOKEN = "RESET_TOKEN";
